Add controllers
smdka/java-shareit pull request #1
Opened 2023-02-09 20:08 UTC by smdka

2023-02-10 17:06 UTC, boristm1 requested changes

2023-02-10 17:06 UTC, boristm1 commented on src/main/java/ru/practicum/shareit/item/dto/ItemDto.java
> +    private long id;
лучше сделать все поля DTO  final, чтобы DTO нельзя было изменить после создания: 
[https://medium.com/nuances-of-programming/не-самые-очевидные-советы-по-написанию-dto-на-java-16ad8419d36b](https://medium.com/nuances-of-programming/%D0%BD%D0%B5-%D1%81%D0%B0%D0%BC%D1%8B%D0%B5-%D0%BE%D1%87%D0%B5%D0%B2%D0%B8%D0%B4%D0%BD%D1%8B%D0%B5-%D1%81%D0%BE%D0%B2%D0%B5%D1%82%D1%8B-%D0%BF%D0%BE-%D0%BD%D0%B0%D0%BF%D0%B8%D1%81%D0%B0%D0%BD%D0%B8%D1%8E-dto-%D0%BD%D0%B0-java-16ad8419d36b)

2023-02-10 17:06 UTC, boristm1 commented on src/main/java/ru/practicum/shareit/item/service/ItemService.java
> +    ItemDto updateById(long itemId, long userId, Item itemWithUpdates);
нужно ли возвращать вещь, которую мы же и передали для обновления?

2023-02-10 17:06 UTC, boristm1 commented on src/main/java/ru/practicum/shareit/item/model/Item.java
> +    public void updateFrom(Item itemWithUpdates) {
в классах модели не должно быть никакой бизнес-логики и маппинга: бизнес-логика должна быть только в сервисах, а маппинг в мапперах

2023-02-10 17:06 UTC, boristm1 commented on src/main/java/ru/practicum/shareit/item/storage/ItemStorageImpl.java
> +            throw new ItemNotFoundException(String.format("У пользователя с id = %d нет вещей", userId));
это бизнес-исключение (с сообщением пользователю) и должно быть в сервисном слое (он отвечает за бизнес-логику), репозитории не должны заботиться о том, какие сообщения посылать пользователю - это должен делать сервис (представь, что к сервису подключили другой репозиторий, а там другие сообщения для одного и того же бизнес-кейса).
В данном случае проще вернуть false, если вещь не найдена, и true при успешном обновлении

2023-02-10 17:06 UTC, boristm1 commented on src/main/java/ru/practicum/shareit/item/service/ItemService.java
> +    ItemDto add(long userId, Item item);
в интерфейсе одного слоя (сервисный слой, слой доступа к данным и т. п.) лучше использовать либо модели, либо DTO, но не оба одновременно, т. к. это порождает лишние зависимости.

И нужно ли возвращать вещь, которую мы же и добавили?

2023-02-10 17:06 UTC, boristm1 commented on src/main/java/ru/practicum/shareit/user/storage/UserStorageImpl.java
> +    private static final Map<Long, User> users = new HashMap<>();
в системе должен быть только 1 экземпляр UserStorageImpl, так что нет необходимости хранить в статическом поле - лучше убрать static

2023-02-10 18:25 UTC, smdka commented on src/main/java/ru/practicum/shareit/item/dto/ItemDto.java
> +    private long id;
Исправил

2023-02-11 06:15 UTC, smdka commented on src/main/java/ru/practicum/shareit/item/service/ItemService.java
> +    ItemDto updateById(long itemId, long userId, Item itemWithUpdates);
Требуется по тестам Postman

2023-02-11 09:24 UTC, smdka commented on src/main/java/ru/practicum/shareit/item/storage/ItemStorageImpl.java
> +            throw new ItemNotFoundException(String.format("У пользователя с id = %d нет вещей", userId));
Исправил.
Вещь требуется вернуть после обновления по тестам Postman

2023-02-11 09:25 UTC, smdka commented on src/main/java/ru/practicum/shareit/item/service/ItemService.java
> +    ItemDto add(long userId, Item item);
Исправил
Вещь нужно возвращать по тестам Postman

2023-02-11 09:25 UTC, smdka commented on src/main/java/ru/practicum/shareit/user/storage/UserStorageImpl.java
> +    private static final Map<Long, User> users = new HashMap<>();
Исправил

2023-02-11 09:48 UTC, smdka commented on src/main/java/ru/practicum/shareit/item/model/Item.java
> +    public void updateFrom(Item itemWithUpdates) {
Исправил

2023-02-12 18:22 UTC, boristm1 requested changes

2023-02-12 18:22 UTC, boristm1 commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +    public void updateFrom(Item item, Item itemDto) {
лучше сделать приватным

2023-02-12 18:22 UTC, boristm1 commented on src/main/java/ru/practicum/shareit/item/storage/ItemStorageImpl.java
> +    public Item updateByItemId(Item updatedItem) {
этот метод ничего не сохраняет в items, а тесты проходят только потому, что в сервисе сначала получается item из items, а потом обновляются его поля (а т. к. этот item уже есть в items, то в updateByItemId можно вообще ничего не делать - можно оставить только return updatedItem и тесты будут проходить) - нужно сохранять updatedItem в items

2023-02-12 18:22 UTC, boristm1 commented on src/main/java/ru/practicum/shareit/user/storage/UserStorageImpl.java
> +    public User updateById(User userWithUpdates) {
нужно сохранять userWithUpdates в users (см. коммент для ItemStorageImpl)

2023-02-12 18:22 UTC, boristm1 commented on src/main/java/ru/practicum/shareit/item/storage/ItemStorage.java
> +    Item save(Item item);
можно сделать void, т. к. возвращается тот же item, который мы передаем (а вот сервис уже вернет этот item в контроллер)

2023-02-12 18:22 UTC, boristm1 commented on src/main/java/ru/practicum/shareit/item/storage/ItemStorage.java
> +    Item updateByItemId(Item updatedItem);
можно сделать void, т. к. возвращается тот же updatedItem, который мы передаем (а вот сервис уже вернет этот updatedItem в контроллер)

2023-02-12 18:22 UTC, boristm1 commented on src/main/java/ru/practicum/shareit/user/storage/UserStorage.java
> +    User save(User user);
можно сделать void, т. к. возвращается тот же user, который мы передаем (а вот сервис уже вернет этот user в контроллер)

2023-02-12 18:22 UTC, boristm1 commented on src/main/java/ru/practicum/shareit/user/storage/UserStorage.java
> +    User updateById(User userWithUpdates);
можно сделать void, т. к. возвращается тот же userWithUpdates, который мы передаем (а вот сервис уже вернет этот userWithUpdates в контроллер)

2023-02-12 18:22 UTC, boristm1 commented on src/main/java/ru/practicum/shareit/user/service/UserServiceImpl.java
> +    public void updateFrom(User userToUpdate, User userWithUpdates) {
лучше сделать приватным

2023-02-12 18:36 UTC, smdka commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +    public void updateFrom(Item item, Item itemDto) {
Исправил

2023-02-12 18:50 UTC, smdka commented on src/main/java/ru/practicum/shareit/item/storage/ItemStorageImpl.java
> +    public Item updateByItemId(Item updatedItem) {
Исправил

2023-02-12 18:52 UTC, smdka commented on src/main/java/ru/practicum/shareit/user/storage/UserStorageImpl.java
> +    public User updateById(User userWithUpdates) {
Исправил

2023-02-12 18:52 UTC, smdka commented on src/main/java/ru/practicum/shareit/item/storage/ItemStorage.java
> +    Item save(Item item);
Обсудили

2023-02-12 18:54 UTC, smdka commented on src/main/java/ru/practicum/shareit/item/storage/ItemStorage.java
> +    Item updateByItemId(Item updatedItem);
Исправил

2023-02-12 18:55 UTC, smdka commented on src/main/java/ru/practicum/shareit/user/storage/UserStorage.java
> +    User save(User user);
Обсудили

2023-02-12 18:56 UTC, smdka commented on src/main/java/ru/practicum/shareit/user/storage/UserStorage.java
> +    User updateById(User userWithUpdates);
Исправил

2023-02-13 16:47 UTC, boristm1 approved these changes

2023-02-13 16:49 UTC, boristm1 approved these changes
Все замечания устранены

2023-02-13 16:55 UTC, merged